'''
Created on Feb 28, 2014

https://projecteuler.net/problem=44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

@author: Cawb07, Glix
'''
from time import time


start = time()

#n(n+1)/2 n(3n-1)/2 n(2n-1)

switch = False
n = m = 0
while(True)
	for(i<j,i++)
		for(j<k,j++)
			if (n(n+1)/2) == (n(3n-1)/2)
				switch = True
			n = n++
		if switch && (m(m+1)/2) == m(2m-1)


elapsed = time() - start
print( "The elapsed time is {0} seconds.".format(elapsed) )